(function(root){
 'use strict'; const seen=new Map(),p=()=>typeof SB_PROFILE!=='undefined'?SB_PROFILE:null,sb=()=>root.SB;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function kind(m){m=String(m).toLowerCase();return /401|403|jwt|rls|permission/.test(m)?['authorization','high']:/500|undefined|not a function|syntax/.test(m)?['application','critical']:/network|fetch|offline|timeout|desconect/.test(m)?['connection','high']:['unknown','medium'];}
 async function record(x={}){if(!sb()||!p()?.id)return;const message=String(x.message||'Erro sem mensagem').slice(0,1200),key=[x.source,x.action,message].join('|'),now=Date.now();if(now-(seen.get(key)||0)<60000)return;seen.set(key,now);const [error_type,severity]=kind(message);try{await sb().from('app_error_events').insert({user_id:p().id,source:x.source||'frontend',screen:x.screen||location.hash||location.pathname,action:x.action||null,error_code:x.code||null,error_type,severity,message,technical_details:{stack:String(x.stack||'').slice(0,4000),url:location.href,userAgent:navigator.userAgent}});}catch(_){}}
 root.addEventListener('error',e=>record({source:'window.error',message:e.message,stack:e.error?.stack,code:e.error?.name})); root.addEventListener('unhandledrejection',e=>record({source:'unhandledrejection',message:e.reason?.message||e.reason,stack:e.reason?.stack}));
 function css(){if(document.getElementById('nf-health-css'))return;const e=document.createElement('style');e.id='nf-health-css';e.textContent='#nf-health-button{position:fixed;right:18px;bottom:18px;z-index:9997;border:0;border-radius:24px;background:#0f766e;color:#fff;padding:11px 16px;font-weight:800;box-shadow:0 8px 26px #0003}#nf-health-modal{position:fixed;inset:0;z-index:9998;background:#0f172acc;display:grid;place-items:center;padding:16px}#nf-health-modal[hidden]{display:none}#nf-health-card{width:min(920px,96vw);max-height:88vh;overflow:auto;background:#fff;border-radius:16px;padding:20px;color:#172033}#nf-health-card table{width:100%;border-collapse:collapse;font-size:.75rem}#nf-health-card th,#nf-health-card td{padding:8px;border-bottom:1px solid #e5e7eb;text-align:left}.nf-ha{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.nf-ha button{border:0;border-radius:8px;padding:9px 12px;font-weight:700}.nf-hp{background:#0f766e;color:#fff}';document.head.appendChild(e);}
 async function load(){const b=document.getElementById('nf-health-body');if(!b)return;b.innerHTML='<p>Carregando diagnóstico…</p>';const [a,c]=await Promise.all([sb().from('health_scan_runs').select('*').order('started_at',{ascending:false}).limit(10),sb().from('app_error_events').select('*').order('occurred_at',{ascending:false}).limit(50)]);if(a.error||c.error){b.innerHTML='<p style="color:#b91c1c">Falha ao carregar: '+esc(a.error?.message||c.error?.message)+'</p>';return;}const errors=c.data||[],open=errors.filter(e=>!['resolved','ignored','auto_fixed'].includes(e.status)),last=a.data?.[0];b.innerHTML=`<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px"><div class="card"><b>Status</b><br>${esc(last?.status||'Aguardando')}</div><div class="card"><b>Erros abertos</b><br>${open.length}</div><div class="card"><b>Última varredura</b><br>${last?new Date(last.started_at).toLocaleString('pt-BR'):'Não executada'}</div></div><h3>Ocorrências recentes</h3><table><tr><th>Data</th><th>Gravidade</th><th>Tipo</th><th>Mensagem</th><th>Situação</th></tr>${errors.map(e=>`<tr><td>${new Date(e.occurred_at).toLocaleString('pt-BR')}</td><td>${esc(e.severity)}</td><td>${esc(e.error_type)}</td><td>${esc(e.message)}${e.suggested_fix?'<br><small>Correção: '+esc(e.suggested_fix)+'</small>':''}</td><td>${esc(e.status)}</td></tr>`).join('')||'<tr><td colspan="5">Nenhum erro registrado.</td></tr>'}</table>`;}
 async function scan(){const e=document.getElementById('nf-health-scan');e.disabled=true;try{const r=await sb().rpc('run_nexofield_health_scan',{p_trigger_type:'manual'});if(r.error)throw r.error;await load();}catch(x){record({source:'health_panel',action:'run_scan',message:x.message,stack:x.stack});alert('Falha na varredura: '+x.message);}finally{e.disabled=false;}}
 function mount(){if(p()?.tipo!=='admin'||document.getElementById('nf-health-button'))return;css();document.body.insertAdjacentHTML('beforeend','<button id="nf-health-button">Saúde do sistema</button><div id="nf-health-modal" hidden><section id="nf-health-card"><div style="display:flex;justify-content:space-between"><h2>Saúde do NexoField</h2><button id="nf-health-x">Fechar</button></div><div class="nf-ha"><button id="nf-health-scan" class="nf-hp">Executar varredura agora</button><button id="nf-health-refresh">Atualizar painel</button></div><div id="nf-health-body"></div></section></div>');const m=document.getElementById('nf-health-modal');document.getElementById('nf-health-button').onclick=()=>{m.hidden=false;load()};document.getElementById('nf-health-x').onclick=()=>m.hidden=true;document.getElementById('nf-health-refresh').onclick=load;document.getElementById('nf-health-scan').onclick=scan;}
 async function daily(){if(p()?.tipo!=='admin'||!sb())return;const key='nf-health-last-daily-v1',last=Number(localStorage.getItem(key)||0);if(Date.now()-last<86400000)return;localStorage.setItem(key,String(Date.now()));const r=await sb().rpc('run_nexofield_health_scan',{p_trigger_type:'scheduled'});if(r.error){localStorage.removeItem(key);record({source:'health_daily',action:'scheduled_scan',message:r.error.message});}}
 setInterval(()=>{mount();daily();},1500);document.addEventListener('DOMContentLoaded',()=>{mount();daily()});root.NexoFieldHealth={record,load,scan,mount,daily};
})(window);
