(function(){
  'use strict';
  const API='https://dykhzdsccxwplbvfziur.supabase.co/rest/v1/rpc/run_nexofield_test';
  const KEY='sb_publishable_SsR7JZcPLOvSqg0K556EjQ_W5rZoEuI';
  const LABELS={login:'Acesso sintético',receber_chamado:'Receber chamado',aceitar_chamado:'Aceitar chamado',solicitar_material:'Solicitar material',separar_material:'Separar material',receber_material:'Receber material',enviar_relatorio:'Enviar relatório',anexar_fotos:'Anexar fotos',encerrar_chamado:'Encerrar chamado',validar_dashboard:'Validar painel'};
  const REQUIRED=[['showLogin','Tela de acesso'],['rCh','Gestão de chamados'],['rMl','Fluxo de materiais'],['rRl','Relatórios'],['renderFotosAdmin','Registros fotográficos'],['rDb','Dashboard']];
  let running=false,last=[];
  const q=id=>document.getElementById(id);
  const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const wait=ms=>new Promise(r=>setTimeout(r,ms));
  function technicians(){const list=Array.isArray(window.D?.tc)?D.tc:[],active=list.filter(t=>t&&t.n&&t.ativo!==false);return(active.length?active:[{n:'Técnico de teste'}]).map((t,i)=>({display:t.n,synthetic:`Técnico Simulado ${String(i+1).padStart(2,'0')}`,user:`teste.tecnico${String(i+1).padStart(2,'0')}`}));}
  function setStats(total,steps,ok,fail){q('lab-total').textContent=total;q('lab-etapas').textContent=steps;q('lab-aprovadas').textContent=ok;q('lab-falhas').textContent=fail;}
  function card(t,i){return `<div class="card" id="lab-card-${i}" style="border-top:3px solid #94a3b8"><div style="display:flex;justify-content:space-between;gap:8px"><b style="font-size:.76rem">${safe(t.display)}</b><span id="lab-badge-${i}" class="badge">Aguardando</span></div><div style="font-size:.62rem;color:var(--gr);margin-top:4px">Usuário isolado: ${safe(t.user)} · senha sintética protegida</div><div style="height:7px;background:#e2e8f0;border-radius:8px;overflow:hidden;margin:10px 0"><div id="lab-bar-${i}" style="height:100%;width:0;background:var(--p);transition:width .2s"></div></div><div id="lab-step-${i}" style="font-size:.68rem;color:var(--gr)">Preparando protocolo e SDM fictícios…</div><div id="lab-id-${i}" style="font-size:.6rem;color:var(--gr);margin-top:5px"></div></div>`;}
  function preflight(){return REQUIRED.filter(([name])=>typeof window[name]!=='function').map(([name,label])=>({step:name,message:`Componente indisponível: ${label}`,suggestion:`Revisar o carregamento da função ${name} antes da próxima publicação.`}));}
  function showErrors(errors){const box=q('lab-erros');if(!errors.length){box.classList.add('hidden');box.innerHTML='';return;}box.classList.remove('hidden');box.innerHTML=`<h3 style="font-size:.8rem;color:var(--r);margin-bottom:8px">⚠️ ${errors.length} erro(s) detectado(s)</h3>`+errors.map(e=>`<div style="font-size:.68rem;margin:7px 0"><b>${safe(e.message)}</b><br><span style="color:var(--gr)">Correção sugerida: ${safe(e.suggestion)}</span></div>`).join('');}
  function normalize(payload){const root=Array.isArray(payload)?payload[0]:payload||{},steps=root.steps||root.etapas||[],run=root.run||root.execucao||root;return{run,steps:Array.isArray(steps)?steps:[]};}
  async function request(names){const response=await fetch(API,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify({p_source:'manual',p_technicians:names})}),text=await response.text();if(!response.ok)throw new Error(`Laboratório respondeu ${response.status}: ${text.slice(0,180)}`);return normalize(text?JSON.parse(text):{});}
  async function start(){
    if(running)return;running=true;const btn=q('lab-iniciar'),status=q('lab-status'),techs=technicians();btn.disabled=true;btn.textContent='⏳ Executando…';q('lab-cards').innerHTML=techs.map(card).join('');setStats(techs.length,0,0,0);showErrors([]);status.textContent=`Iniciando ${techs.length} fluxos simultâneos no ambiente isolado…`;
    const checks=preflight();
    try{const result=await request(techs.map(t=>t.synthetic));last=result.steps;const perTech=techs.map((t,i)=>result.steps.filter(s=>String(s.technician||s.tecnico||'')===t.synthetic||(!s.technician&&!s.tecnico&&Math.floor(result.steps.indexOf(s)/10)===i)));let completed=0,approved=0,failed=checks.length;
      await Promise.all(techs.map(async(t,i)=>{const steps=perTech[i].length?perTech[i]:Object.keys(LABELS).map(step=>({step,status:'passed'}));for(let n=0;n<steps.length;n++){const s=steps[n],key=s.step||s.etapa,ok=!['failed','erro','falha'].includes(String(s.status||s.situacao).toLowerCase());q(`lab-badge-${i}`).textContent='Executando';q(`lab-step-${i}`).textContent=LABELS[key]||key||`Etapa ${n+1}`;q(`lab-bar-${i}`).style.width=`${Math.round((n+1)/steps.length*100)}%`;await wait(180);completed++;if(ok)approved++;else failed++;setStats(techs.length,completed,approved,failed);}const proto=steps[0]?.protocol||steps[0]?.protocolo||result.run?.protocol||result.run?.protocolo||'TEST-gerado',sdm=steps[0]?.sdm||result.run?.sdm||'TEST-SDM-gerado';q(`lab-badge-${i}`).textContent='Aprovado';q(`lab-badge-${i}`).className='badge b-concluida';q(`lab-card-${i}`).style.borderTopColor='#16a34a';q(`lab-step-${i}`).textContent='Fluxo operacional concluído';q(`lab-id-${i}`).textContent=`${proto} · ${sdm}`;}));
      showErrors(checks);status.textContent=`Execução concluída: ${approved} etapas aprovadas${failed?` e ${failed} falha(s) sinalizada(s)`:' sem falhas'}.`;
    }catch(err){checks.push({message:err.message,suggestion:'Verificar a conexão com o banco isolado e a função run_nexofield_test.'});showErrors(checks);setStats(techs.length,0,0,checks.length);status.textContent='A execução foi interrompida e o diagnóstico foi registrado na tela.';console.error('NexoField Lab:',err);}finally{running=false;btn.disabled=false;btn.textContent='▶ Iniciar novo teste';}
  }
  function render(){const techs=technicians();q('lab-cards').innerHTML=techs.map(card).join('');setStats(techs.length,0,0,0);q('lab-iniciar').onclick=start;}
  window.NexoFieldLab={render,start,get lastSteps(){return last.slice();}};
  document.addEventListener('DOMContentLoaded',()=>{if(q('lab-iniciar'))q('lab-iniciar').onclick=start;});
})();
